# $NetBSD$

GITHUB_PROJECT=	waydroid
GITHUB_TAG=	refs/tags/1.4.2
DISTNAME=	1.4.2
PKGNAME=	${GITHUB_PROJECT}-${DISTNAME}
CATEGORIES=	linux
MASTER_SITES=	${MASTER_SITE_GITHUB:=waydroid/}
DIST_SUBDIR=	${GITHUB_PROJECT}

MAINTAINER=	users@NetBSD.org
HOMEPAGE=	https://github.com/waydroid/waydroid/
COMMENT=	boot a full Android system on a regular GNU/Linux system
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/waydroid-1.4.2
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
