# $NetBSD$

GITHUB_PROJECT=	blivet-gui
DISTNAME=	blivet-gui-2.4.1
CATEGORIES=	linux
MASTER_SITES=	${MASTER_SITE_GITHUB:=storaged-project/}
GITHUB_RELEASE=	2.4.1

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/storaged-project/blivet-gui/
COMMENT=	GUI tool for storage configuration using blivet library
LICENSE=	gnu-gpl-v2

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
