# $NetBSD$

DISTNAME=	arcload-0.5
CATEGORIES=	linux
MASTER_SITES=	ftp://ftp.linux-mips.org/pub/linux/mips/people/skylark/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	ftp://ftp.linux-mips.org/pub/linux/mips/people/skylark/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

.include "../../mk/bsd.pkg.mk"
