# $NetBSD$

DISTNAME=	ss5-3.8.9-8
CATEGORIES=	linux
MASTER_SITES=	https://jaist.dl.sourceforge.net/project/ss5/ss5/3.8.9-8/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://jaist.dl.sourceforge.net/project/ss5/ss5/3.8.9-8/
COMMENT=	Generic Security Services Application Programming Interface
LICENSE=	gnu-gpl-v2

WRKSRC=		${WRKDIR}/ss5-3.8.9
GNU_CONFIGURE=	yes

.include "../../mk/pam.buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
