# $NetBSD: Makefile,v 1.426 2024/05/03 20:39:24 ryoon Exp $
#

COMMENT=	Fonts

SUBDIR+=	nerd-fonts-3270
SUBDIR+=	nerd-fonts-Agave
SUBDIR+=	nerd-fonts-AnonymousPro
SUBDIR+=	nerd-fonts-Arimo
SUBDIR+=	nerd-fonts-AurulentSansMono
SUBDIR+=	nerd-fonts-BigBlueTerminal
SUBDIR+=	nerd-fonts-BitstreamVeraSansMono
SUBDIR+=	nerd-fonts-CascadiaCode
SUBDIR+=	nerd-fonts-CodeNewRoman
SUBDIR+=	nerd-fonts-Cousine
SUBDIR+=	nerd-fonts-DaddyTimeMono
SUBDIR+=	nerd-fonts-Hack
SUBDIR+=	nerd-fonts-IBMPlexMono
SUBDIR+=	nerd-fonts-JetBrainsMono
SUBDIR+=	nerd-fonts-Meslo
SUBDIR+=	nerd-fonts-SourceCodePro
SUBDIR+=	nerd-fonts-iA-Writer

.include "../mk/misc/category.mk"
