# $NetBSD$

DISTNAME=	TLP-1.7.0
CATEGORIES=	linux
MASTER_SITES=	https://codeload.github.com/linrunner/TLP/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://codeload.github.com/linrunner/TLP/
COMMENT=	utils saving laptop battery power no need technical details
LICENSE=	gnu-gpl-v2

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
