#!/bin/bash

#mkdir -pv native/{bin,boot,etc/{opt,sysconfig},home,mnt,opt}
mkdir -pv native/{bin,boot,etc/{opt,sysconfig}}
#mkdir -pv native/{media/{floppy,cdrom},sbin,srv,var}
mkdir -pv native/{sbin,var}
install -dv -m 0750 native/root
mkdir -pv native/usr/{,local/}{bin,include,lib,sbin,src}
mkdir -pv native/usr/{,local/}share/{color,dict,doc,info,locale,man}
mkdir -pv  native/usr/{,local/}share/{misc,terminfo,zoneinfo}
mkdir -pv  native/usr/libexec
mkdir -pv native/usr/{,local/}share/man/man{1..8}

case $(uname -m) in
	x86_64) mkdir -pv native/lib64 ;;
esac

mkdir -pv native/var/{log,mail,spool}
ln -sv ../run native/var/
ln -sv ../run/lock native/var/lock
mkdir -pv native/var/{opt,cache,lib/{color,misc,locate},local}

#ln -sv ../proc/self/mounts /etc/mtab

install --directory --mode=0755 --owner=root --group=root native/etc/profile.d
install --directory --mode=0755 --owner=root --group=root native/etc/bash_completion.d
