#!/bin/bash
#
# automatically generated by
#
#   'work/VirtualBox-7.0.12/configure '
#
# It will be completely overwritten if configure is executed again.
# Make sure you source this file once before you start to build VBox.
#

KBUILD_HOST="linux"
KBUILD_HOST_ARCH="amd64"
KBUILD_TARGET="linux"
KBUILD_TARGET_ARCH="amd64"
KBUILD_TARGET_CPU="blend"
KBUILD_TYPE="release"
export KBUILD_HOST KBUILD_HOST_ARCH KBUILD_TARGET KBUILD_TARGET_ARCH KBUILD_TARGET_CPU KBUILD_TYPE

# Legacy - do not use:
BUILD_PLATFORM="$KBUILD_HOST"
BUILD_PLATFORM_ARCH="$KBUILD_HOST_ARCH"
BUILD_TARGET="$KBUILD_TARGET"
BUILD_TARGET_ARCH="$KBUILD_TARGET_ARCH"
BUILD_TARGET_CPU="$KBUILD_TARGET_CPU"
BUILD_TYPE="$KBUILD_TYPE"
export BUILD_PLATFORM BUILD_PLATFORM_ARCH BUILD_TARGET BUILD_TARGET_ARCH BUILD_TARGET_CPU BUILD_TYPE

KBUILD_PATH="/root/pkglinux-pkgsrc/native/vbox7/work/VirtualBox-7.0.12/kBuild"
KBUILD_DEVTOOLS="/root/pkglinux-pkgsrc/native/vbox7/work/VirtualBox-7.0.12/tools"
path_kbuild_bin="$KBUILD_PATH/bin/$BUILD_TARGET.$BUILD_PLATFORM_ARCH"
path_tools_bin="$KBUILD_DEVTOOLS/$BUILD_TARGET.$BUILD_PLATFORM_ARCH/bin"
echo "$PATH" | grep -q "$path_kbuild_bin" || PATH="$path_kbuild_bin:$PATH"
echo "$PATH" | grep -q "$path_tools_bin"  || PATH="$path_tools_bin:$PATH"
export KBUILD_PATH KBUILD_DEVTOOLS PATH
unset path_kbuild_bin path_tools_bin

# Legacy - do not use:
PATH_KBUILD=${KBUILD_PATH}
PATH_DEVTOOLS=${KBUILD_DEVTOOLS}
export PATH_KBUILD PATH_DEVTOOLS

