# $NetBSD$

DISTNAME=	silo-1.4.14
CATEGORIES=	linux
MASTER_SITES=	http://cross-lfs.org/files/packages/3.0.0/SYSVINIT/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://cross-lfs.org/files/packages/3.0.0/SYSVINIT/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
