# $NetBSD$

DISTNAME=	killproc-2.24
CATEGORIES=	linux
MASTER_SITES=	https://codeload.github.com/bitstreamout/killproc/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://codeload.github.com/bitstreamout/killproc/
COMMENT=	three tools for process controlling
LICENSE=	gnu-gpl-v2

USE_TOOLS+=	gmake

MAKE_ENV+=	PREFIX=${PREFIX}

.include "../../mk/bsd.pkg.mk"
