$NetBSD: patch-Cargo.toml,v 1.1 2022/03/28 14:11:01 wiz Exp $

Compatibility with rust<1.59.

--- Cargo.toml.orig	2022-03-27 00:08:44.000000000 +0000
+++ Cargo.toml
@@ -6,7 +6,6 @@ members = ["crates/*"]
 codegen-units = 1
 lto = "thin"
 opt-level = 3
-strip = "debuginfo"
 
 [profile.bench]
 lto = true
