# $NetBSD$

DISTNAME=	v5.4
PKGNAME=	${DISTNAME:S,^v,,}
CATEGORIES=	linux
MASTER_SITES=	https://codeload.github.com/proot-me/proot/tar.gz/refs/tags/
EXTRACT_SUFX=	.0

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://codeload.github.com/proot-me/proot/tar.gz/refs/tags/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}
USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
