# $NetBSD$

DISTNAME=	duf-0.8.1
CATEGORIES=	linux
MASTER_SITES=	${MASTER_SITE_GITHUB:=muesli/duf/releases/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/muesli/duf/releases/ # TODO: check
COMMENT=	Disk Usage/Free Utility
LICENSE=	gnu-gpl-v2

USE_LANGUAGES=	# none

.include "../../mk/bsd.pkg.mk"
