# $NetBSD$

DISTNAME=	libptp2-1.2.0
CATEGORIES=	linux
MASTER_SITES=	https://sourceforge.net/projects/libptp/files/libptp2/libptp2-1.2.0/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://sourceforge.net/projects/libptp/files/libptp2/libptp2-1.2.0/
COMMENT=	does things that you can't do with gphoto2
LICENSE=	gnu-gpl-v2

GNU_CONFIGURE=	yes
USE_LIBTOOL=	yes

.include "../../devel/libusb/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
