# $NetBSD$

GITHUB_PROJECT=	calamares
DISTNAME=	calamares-3.2.61
CATEGORIES=	linux
MASTER_SITES=	${MASTER_SITE_GITHUB:=calamares/}
GITHUB_RELEASE=	v3.2.61

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/calamares/calamares/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_CMAKE=		yes
USE_PKGLOCALEDIR=	yes
USE_LANGUAGES=		c c++

.include "../../mk/bsd.pkg.mk"
