# $NetBSD$

DISTNAME=	dwarfs-0.6.1
CATEGORIES=	linux
MASTER_SITES=	https://codeload.github.com/mhx/dwarfs/releases/

MAINTAINER=	use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://codeload.github.com/mhx/dwarfs/releases/
COMMENT=	fast high compression read-only file system
LICENSE=	gnu-gpl-v2

USE_CMAKE=	yes
USE_LANGUAGES=	c c++

.include "../../devel/git/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
