#!/bin/bash -ue

<< MIT-LICENSE
Copyright (c) 2023 Jianjun Liu<jianjunliu@126.com> https://www.pkglinux.top

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
MIT-LICENSE

echo Starting $0 $@

for arg in "$@"; do
	shift
	case "$arg" in
		"--basedir")	set -- "$@" "-b" ;;
		*)		set -- "$@" "$arg"
	esac
done

_basedir="/root/current"

while getopts 'b:' OPTION; do
	case "$OPTION" in
		b)
			_basedir="$OPTARG" ;;
		*)
			echo "Usage: $0 [ -b basedir ] prefix" >&2
			exit 1 ;;
	esac
done

# Remove all options passed by getopts options
shift "$(($OPTIND -1))"

[[ "$#" -lt 1 ]] && { echo "Usage: $0 [ -b basedir ] prefix" >&2; exit 1; }
[ ${UID} -ne 0 ] && echo "$0 will not be performed when not running as root" && exit 1;
[[ -d "$_basedir/packages.$1" ]] ||  { echo "$_basedir/packages.$1 is not a directory.";exit 1; }

pushd $_basedir/packages.$1/All/
pwd
find . -name '*.tgz' -exec pkg_info -X {} \; > pkg_summary
gzip -f pkg_summary
ls -la pkg_summary*
popd
sync
