# $NetBSD$

DISTNAME=	psplash-0.1
CATEGORIES=	native
MASTER_SITES=	https://downloads.yoctoproject.org/releases/psplash/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://downloads.yoctoproject.org/releases/psplash/
COMMENT=	userspace graphical boot splash screen
LICENSE=	gnu-gpl-v2

GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
