# $NetBSD$

DISTNAME=	dvhtool_1.0.1.orig
CATEGORIES=	linux
MASTER_SITES=	${MASTER_SITE_DEBIAN:=pool/main/d/dvhtool/}

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	http://ftp.debian.org/debian/pool/main/d/dvhtool/ # TODO: check
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

WRKSRC=		${WRKDIR}/dvhtool-1.0.1.orig
GNU_CONFIGURE=	yes

.include "../../mk/bsd.pkg.mk"
